language: ruby

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare

before_script:
  - psql -c "CREATE USER loria WITH PASSWORD 'l0r1A';" -U postgres
  - psql -c "ALTER ROLE loria WITH CREATEDB;" -U postgres
  - psql -c 'create database loria_test' -U postgres 
  - psql -c "ALTER DATABASE loria_test OWNER TO loria;" -U postgres
